name: Flutter Web CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master"]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Flutter SDK
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter doctor

    - name: Enable Web Support
      run: flutter config --enable-web

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Web App
      run: flutter build web --release

    - name: Upload Web Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: build/web/
