name: Flutter Linux & Web CI

on:
  push:
    branches: [ "master"]  # Run on pushes to master or main branch
  pull_request:
    branches: [ "master"]  # Run on pull requests to these branches
  workflow_dispatch:  # Allows manual triggering of workflow

jobs:
  # Linux Build Job
  build-linux:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "stable"  # Use the latest stable version of Flutter

    - name: Build Linux Binary
      run: flutter build linux --release

    - name: Upload Linux Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-binary
        path: build/linux/x64/release/bundle/

  # Web Build Job
  build-web:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "stable"

    - name: Build Web Version
      run: flutter build web --release

    - name: Upload Web Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: build/web/
