name: Flutter Linux & Web CI

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  # Linux Build Job
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

    - name: Set up Flutter SDK
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter doctor

    - name: Build Linux Binary
      run: flutter build linux --release

    - name: Upload Linux Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-binary
        path: build/linux/x64/release/bundle/

  # Web Build Job
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Flutter SDK
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter doctor

    - name: Build Web Version
      run: flutter build web --release

    - name: Upload Web Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: build/web/

